apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ovirt-cluster-provider-manager-secrets
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ovirt-cluster-provider-manager-secrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: ovirt-cluster-provider-system
